import puppeteer from "puppeteer-core";
const CHROME = "/home/synthsloth/.cache/ms-playwright/chromium-1234/chrome-linux64/chrome";
const URL = "https://structures-namespace-officers-humor.trycloudflare.com/";
const b = await puppeteer.launch({ executablePath: CHROME, headless: true, args: ["--no-sandbox"] });
const p = await b.newPage();
await p.setViewport({ width: 1000, height: 900 });
const errs = [];
p.on("pageerror", (e) => errs.push(String(e).slice(0, 70)));
await p.goto(URL, { waitUntil: "networkidle2", timeout: 60000 });
await new Promise((r) => setTimeout(r, 4500));
const h = await p.evaluate(() => document.body.innerText || "");
console.log("banner temp:", /°/.test(h), "| scene div:", await p.evaluate(() => !!document.querySelector(".banner") && !!document.querySelector(".scene-icon")));
console.log("has like class scene-:", await p.evaluate(() => { const el = document.querySelector(".banner"); return el ? el.className.includes("scene-") : false; }));
console.log("intro + more:", /More/.test(h) && /Live weather/.test(h));
console.log("count chips:", /flood alerts/.test(h) || /0 flood alerts/.test(h), "| hazard stories:", /hazard stories/.test(h), "| warnings:", /warnings in force/.test(h));
console.log("telegram+share on hero:", /Telegram alerts/.test(h), "| Share:", /Share|↗/.test(h));
console.log("advisories + official sources:", /Advisories/.test(h) && /Official sources/.test(h));
console.log("RUNTIME:", errs.length ? errs : "none");
await b.close(); process.exit(0);
